{
  "status": "fail",
  "tests": [
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "binary-1-is-decimal-1",
      "status": "error",
      "test_code": "(is (= 1 (binary/to-decimal \"1\")))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "binary-10-is-decimal-2",
      "status": "error",
      "test_code": "(is (= 2 (binary/to-decimal \"10\")))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "binary-11-is-decimal-3",
      "status": "error",
      "test_code": "(is (= 3 (binary/to-decimal \"11\")))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "binary-100-is-decimal-4",
      "status": "error",
      "test_code": "(is (= 4 (binary/to-decimal \"100\")))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "binary-1001-is-decimal-9",
      "status": "error",
      "test_code": "(is (= 9 (binary/to-decimal \"1001\")))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "binary-11010-is-decimal-26",
      "status": "error",
      "test_code": "(is (= 26 (binary/to-decimal \"11010\")))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "binary-10001101000-is-decimal-1128",
      "status": "error",
      "test_code": "(is (= 1128 (binary/to-decimal \"10001101000\")))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "invalid-binary-is-decimal-0",
      "status": "error",
      "test_code": "(is (= 0 (binary/to-decimal \"carrot\")))"
    }
  ],
  "version": 3
}
