{
  "status": "fail",
  "tests": [
    {
      "message": "An unexpected error occurred:\njava.lang.IllegalArgumentException: Don't know how to create ISeq from: sci.impl.vars.SciUnbound",
      "name": "test-one-row",
      "status": "error",
      "test_code": "(testing \"First row\" (is (= (take 1 triangle) [[1]])))"
    },
    {
      "message": "An unexpected error occurred:\njava.lang.IllegalArgumentException: Don't know how to create ISeq from: sci.impl.vars.SciUnbound",
      "name": "test-two-rows",
      "status": "error",
      "test_code": "(testing \"First two rows\" (is (= (take 2 triangle) [[1] [1 1]])))"
    },
    {
      "message": "An unexpected error occurred:\njava.lang.IllegalArgumentException: Don't know how to create ISeq from: sci.impl.vars.SciUnbound",
      "name": "test-three-rows",
      "status": "error",
      "test_code": "(testing \"First 3 rows\" (is (= (take 3 triangle) [[1] [1 1] [1 2 1]])))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "test-third-row",
      "status": "error",
      "test_code": "(testing \"Third row\" (is (= (row 3) [1 2 1])))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "test-fourth-row",
      "status": "error",
      "test_code": "(testing \"Fourth row\" (is (= (row 4) [1 3 3 1])))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "test-fifth-row",
      "status": "error",
      "test_code": "(testing \"Fifth row\" (is (= (row 5) [1 4 6 4 1])))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "triangle-20th-row",
      "status": "error",
      "test_code": "(testing \"20th row\" (is (= (row 20) (let [v [1 19 171 969 3876 11628 27132 50388 75582 92378]] (into v (rseq v))))))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (1) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "triangle-300th-row",
      "status": "error",
      "test_code": "(testing \"300th row\" (is (some? (some #{768408467483699505953134992026497450726137182648496343119395977464120N} (row 300)))))"
    }
  ],
  "version": 3
}
