{
  "status": "fail",
  "tests": [
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "equilateral-all-sides-equal",
      "status": "error",
      "test_code": "(is (true? (triangle/equilateral? 2 2 2)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "equilateral-any-side-is-unequal",
      "status": "error",
      "test_code": "(is (false? (triangle/equilateral? 2 3 2)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "equilateral-no-sides-are-equal",
      "status": "error",
      "test_code": "(is (false? (triangle/equilateral? 5 4 6)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "equilateral-all-zero-sides",
      "status": "error",
      "test_code": "(is (false? (triangle/equilateral? 0 0 0)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "equilateral-sides-may-be-floats",
      "status": "error",
      "test_code": "(is (true? (triangle/equilateral? 0.5 0.5 0.5)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-last-two-sides-equal",
      "status": "error",
      "test_code": "(is (true? (triangle/isosceles? 3 4 4)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-first-two-sides-equal",
      "status": "error",
      "test_code": "(is (true? (triangle/isosceles? 4 4 3)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-first-last-sides-equal",
      "status": "error",
      "test_code": "(is (true? (triangle/isosceles? 4 3 4)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-equilateral-triangles-also-isosceles",
      "status": "error",
      "test_code": "(is (true? (triangle/isosceles? 4 4 4)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-no-sides-equal",
      "status": "error",
      "test_code": "(is (false? (triangle/isosceles? 2 3 4)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-first-triangle-inequality-violation",
      "status": "error",
      "test_code": "(is (false? (triangle/isosceles? 1 1 3)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-second-triangle-inequality-violation",
      "status": "error",
      "test_code": "(is (false? (triangle/isosceles? 1 3 1)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-third-triangle-inequality-violation",
      "status": "error",
      "test_code": "(is (false? (triangle/isosceles? 3 1 1)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "isosceles-sides-may-be-floats",
      "status": "error",
      "test_code": "(is (true? (triangle/isosceles? 0.5 0.4 0.5)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "scalene-no-sides-are-equal",
      "status": "error",
      "test_code": "(is (true? (triangle/scalene? 5 4 6)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "scalene-all-sides-equal",
      "status": "error",
      "test_code": "(is (false? (triangle/scalene? 4 4 4)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "scalene-two-sides-equal",
      "status": "error",
      "test_code": "(is (false? (triangle/scalene? 4 4 3)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "scalene-may-not-violate-triangle-inequality",
      "status": "error",
      "test_code": "(is (false? (triangle/scalene? 7 3 2)))"
    },
    {
      "message": "An unexpected error occurred:\nclojure.lang.ArityException: Wrong number of args (3) passed to: sci.impl.fns/fun/arity-0--3486",
      "name": "scalene-sides-may-be-floats",
      "status": "error",
      "test_code": "(is (true? (triangle/scalene? 0.5 0.4 0.6)))"
    }
  ],
  "version": 3
}
